# Generated by Django 5.2.3 on 2025-07-02 04:45

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='कार्यक्रम नाम')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='विवरण')),
                ('venue', models.CharField(max_length=200, verbose_name='स्थान')),
                ('event_date', models.DateTimeField(verbose_name='कार्यक्रम तिथि')),
                ('registration_deadline', models.DateTimeField(verbose_name='पंजीकरण अंतिम तिथि')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='पंजीकरण शुल्क')),
                ('max_participants', models.PositiveIntegerField(default=100, verbose_name='अधिकतम प्रतिभागी')),
                ('is_published', models.BooleanField(default=True, verbose_name='प्रकाशित')),
                ('is_featured', models.BooleanField(default=False, verbose_name='मुख्य कार्यक्रम')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='श्रेणी')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district', verbose_name='जिला')),
            ],
            options={
                'verbose_name': 'कार्यक्रम',
                'verbose_name_plural': 'कार्यक्रम',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/', verbose_name='छवि')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='कैप्शन')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
            options={
                'verbose_name': 'कार्यक्रम छवि',
                'verbose_name_plural': 'कार्यक्रम छवियां',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='पूरा नाम')),
                ('email', models.EmailField(max_length=254, verbose_name='ईमेल')),
                ('phone', models.CharField(max_length=15, verbose_name='फोन नंबर')),
                ('age', models.PositiveIntegerField(verbose_name='आयु')),
                ('gender', models.CharField(choices=[('M', 'पुरुष'), ('F', 'महिला'), ('O', 'अन्य')], max_length=1, verbose_name='लिंग')),
                ('address', models.TextField(verbose_name='पता')),
                ('occupation', models.CharField(max_length=100, verbose_name='व्यवसाय')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='पुष्ट')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False, verbose_name='भुगतान स्थिति')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district', verbose_name='जिला')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'verbose_name': 'पंजीकरण',
                'verbose_name_plural': 'पंजीकरण',
                'ordering': ['-registration_date'],
            },
        ),
    ]
