# Generated by Django 5.2.3 on 2025-07-02 04:45

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='शीर्षक')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(max_length=500, verbose_name='सारांश')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='मुख्य सामग्री')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='लेखक')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='प्रकाशन तिथि')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='अपडेट तिथि')),
                ('is_published', models.BooleanField(default=True, verbose_name='प्रकाशित')),
                ('is_featured', models.BooleanField(default=False, verbose_name='मुख्य समाचार')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='देखे गए')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='पसंद')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='श्रेणी')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district', verbose_name='जिला')),
            ],
            options={
                'verbose_name': 'समाचार',
                'verbose_name_plural': 'समाचार',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='नाम')),
                ('author_email', models.EmailField(max_length=254, verbose_name='ईमेल')),
                ('content', models.TextField(verbose_name='टिप्पणी')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='स्वीकृत')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
            options={
                'verbose_name': 'टिप्पणी',
                'verbose_name_plural': 'टिप्पणियां',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='छवि')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='कैप्शन')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'verbose_name': 'समाचार छवि',
                'verbose_name_plural': 'समाचार छवियां',
            },
        ),
    ]
