# Generated by Django 5.2.3 on 2025-07-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='श्रेणी नाम')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='विवरण')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'श्रेणी',
                'verbose_name_plural': 'श्रेणियां',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='जिला नाम')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'जिला',
                'verbose_name_plural': 'जिले',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='प्रांतीय युवा प्रकोष्ठ-उत्तर प्रदेश', max_length=200)),
                ('site_description', models.TextField(default='युवाओं के सशक्तिकरण और राष्ट्र निर्माण में योगदान')),
                ('contact_email', models.EmailField(default='info@pranteeyyuva.org', max_length=254)),
                ('contact_phone', models.CharField(default='+91 9415156122', max_length=20)),
                ('contact_address', models.TextField(default='सुल्तानपुर - उत्तर प्रदेश')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(default='+91 9415156122', max_length=20)),
            ],
            options={
                'verbose_name': 'साइट सेटिंग्स',
                'verbose_name_plural': 'साइट सेटिंग्स',
            },
        ),
    ]
