# Generated by Django 5.2.3 on 2025-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='बैनर शीर्षक')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='बैनर छवि')),
                ('link', models.URLField(blank=True, verbose_name='लिंक (वैकल्पिक)')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='क्रम')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'बैनर',
                'verbose_name_plural': 'बैनर',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
