# Generated by Django 5.2.3 on 2025-07-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_members', models.PositiveIntegerField(default=0, verbose_name='सक्रिय सदस्य')),
                ('events_held', models.PositiveIntegerField(default=0, verbose_name='आयोजित कार्यक्रम')),
                ('districts_covered', models.PositiveIntegerField(default=0, verbose_name='जिले कवर')),
                ('social_projects', models.PositiveIntegerField(default=0, verbose_name='समाजसेवा परियोजनाएं')),
            ],
            options={
                'verbose_name': 'Homepage आकड़े',
                'verbose_name_plural': 'Homepage आकड़े',
            },
        ),
    ]
