# Generated by Django 5.2.3 on 2025-07-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='नाम')),
                ('email', models.EmailField(max_length=254, verbose_name='ईमेल')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='फोन नंबर')),
                ('subject', models.CharField(choices=[('general', 'सामान्य पूछताछ'), ('membership', 'सदस्यता'), ('event', 'कार्यक्रम संबंधी'), ('complaint', 'शिकायत'), ('suggestion', 'सुझाव')], max_length=20, verbose_name='विषय')),
                ('message', models.TextField(verbose_name='संदेश')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='भेजा गया')),
                ('is_read', models.BooleanField(default=False, verbose_name='पढ़ा गया')),
                ('is_replied', models.BooleanField(default=False, verbose_name='जवाब दिया गया')),
                ('reply_message', models.TextField(blank=True, verbose_name='जवाब')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='जवाब तिथि')),
            ],
            options={
                'verbose_name': 'संपर्क संदेश',
                'verbose_name_plural': 'संपर्क संदेश',
                'ordering': ['-created_at'],
            },
        ),
    ]
